/***** SYMBOLS ****/

#define BOOL_LOGIC_SYM_TRUE  "T"
#define BOOL_LOGIC_SYM_FALSE "F"
#define BOOL_LOGIC_SYM_VAR   "x_"

#define BOOL_LOGIC_SYM_NOT   "~"
#define BOOL_LOGIC_SYM_OR    "|"
#define BOOL_LOGIC_SYM_AND   "&"
#define BOOL_LOGIC_SYM_IMPLY "->"
#define BOOL_LOGIC_SYM_IFF   "<->"

/***** ENUMS *****/

enum BOOL_LOGIC_TYPE {
	BOOL_LOGIC_TYPE_CONSTANT,
	BOOL_LOGIC_TYPE_VARIABLE,
	BOOL_LOGIC_TYPE_CONNECT,
};

enum BOOL_LOGIC_CONN {
	BOOL_LOGIC_CONN_NOT,
	BOOL_LOGIC_CONN_OR,
	BOOL_LOGIC_CONN_AND,
	BOOL_LOGIC_CONN_IMPLY,
	BOOL_LOGIC_CONN_IFF,
};
